stages:
  - install
  - test

install:
  stage: install
  tags:
    - python
  script:
  - conda env list
  - rm -rf /home/gitlab-runner/.conda/envs/calphy_test
  - conda remove --name calphy_test --all
  - conda config --add channels conda-forge
  - conda create --name calphy_test python pytest tqdm numpy scipy pyyaml mendeleev pylammpsmpi pyscal --force
  - conda env list

test:
  stage: test
  tags:
    - python
  script:
  - source activate calphy_test
  - python setup.py install
  - pytest tests/
