name: calphy
channels:
  - conda-forge
dependencies:
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - openmpi 
  - mpi4py
  - lammps =2022.06.23=*openmpi*_0
  - pylammpsmpi >=0.0.9
  - pyscal
  - matplotlib
  - tqdm
  - uncertainties
