name: calphy
channels:
  - conda-forge
dependencies:
  - python
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - lammps
  - openmpi
  - numpy
  - mpi4py
  - pylammpsmpi
  - matplotlib
  - tqdm
  - uncertainties
  - pydantic >=2.3.0
  - pyscal3
