name: calphy
channels:
  - conda-forge
dependencies:
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - lammps >=2023.03.28
  - openmpi
  - numpy
  - mpi4py
  - pylammpsmpi =0.2.13
  - matplotlib
  - tqdm
  - uncertainties
  - pydantic >=2.3.0
  - pyscal3
