name: calphy2
channels:
  - conda-forge
dependencies:
  - cmake
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - openmpi 
  - mpi4py
  - matplotlib
  - tqdm
  - uncertainties  
  - pydantic >=2.3.0
  - pyscal3
  - pandas
