name: calphy
channels:
  - conda-forge
dependencies:
  - python =3.12
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - lammps =2024.08.29=*_openmpi_*
  - openmpi
  - numpy
  - mpi4py
  - pylammpsmpi >=0.2.13,<=0.2.35
  - matplotlib
  - tqdm
  - uncertainties
  - pydantic >=2.3.0
  - pyscal3
