name: calphy-nolammps
channels:
  - conda-forge
dependencies:
  - python
  - cmake
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - openmpi 
  - numpy
  - mpi4py
  - pylammpsmpi
  - matplotlib
  - tqdm
  - pydantic >=2.3.0
  - pyscal3
