name: calphy
channels:
  - conda-forge
dependencies:
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - openmpi 
  - mpi4py
  - lammps =2021.09.29=*openmpi*_2
  - pylammpsmpi
  - pyscal
  - matplotlib
  - tqdm
