name: calphy-docs
channels:
  - conda-forge
dependencies:
  - python
  - pytest
  - scipy
  - pyyaml
  - mendeleev
  - openmpi 
  - numpy
  - mpi4py
  - pylammpsmpi
  - pyscal3
  - matplotlib
  - tqdm
  - pydantic >=2.3.0
  - pip:
    - sphinx==5.3.0
    - sphinx_rtd_theme
    - myst_parser
    - furo
    - nbsphinx
    - sphinx_inline_tabs
    - sphinx_copybutton
    - sphinx_design
    - docutils==0.19
