
name: pytint testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:    
    strategy:
      matrix:
        os: [ubuntu-latest,]
        python-version: [3.7]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v1
      env:
        # Increase this value to reset cache if etc/example-environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: calphy
        channel-priority: strict
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
   
    - name: run tests
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install pytest
        pip install pytest-cov
        pytest tests/
    
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build
        --user
    
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags') || github.event_name == 'release'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
