
name: calphy testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        include:
          - operating-system: ubuntu-latest
            python-version: 3.11
    steps:
    - uses: actions/checkout@v4
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v4
      with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge
          environment-file: environment.yml   
    - name: run tests
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install pytest
        pip install pytest-cov
        pytest tests/
        cd examples/example_01
        #calphy_kernel -i input.yaml -k 0 -s True
